# Generated by Django 4.1.7 on 2023-04-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sos',
            new_name='sos2',
        ),
    ]
